### ISSUE TITLE
请问能帮帮我吗？

### ISSUE THREAD

**Issue by wwwyuhao** [zjpyb/MSI-GE62-6QC-Hackintosh#1]
我在安装的时候出现一个禁止通行的标志，请问我该如何解决这个问题？或者你能告诉我用这个配置安装mojave的流程吗？感谢。

**Comment by zjpyb** [comment]
安装的话，建议直接用通用的config安装，因为正常运行系统的config，不一定能用来安装系统
你可以试下这个帖子的efi http://bbs.pcbeta.com/viewthread-1760262-1-1.html

**Comment by wwwyuhao** [comment]
> 安装的话，建议直接用通用的配置安装，因为正常运行系统的配置，不一定能用来安装系统
> 你可以试下这个帖子的efi [http://bbs.pcbeta.com/viewthread-1760262-1-1 html的](http://bbs.pcbeta.com/viewthread-1760262-1-1.html)

好的，谢谢。
